
spring:
  application:
    name: service-hello
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# hystrix dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
