server:
  port: 8889

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:tzrough/SpringCloudConfig.git
          search-paths: config
          username:
          password:
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
